### ISSUE TITLE
Get SQL table expectations on the same page

### ISSUE THREAD

**Issue by loshprung** [maddiewaldie/COEN-174-Project#44]
SQL table structure is currently:

#### Accounts

| Field    | Type             | Null | Key | Default | Extra          |
|----------|------------------|------|-----|---------|----------------|
| id       | int(10) unsigned | NO   | PRI | NULL    | auto_increment |
| name     | varchar(256)     | NO   | UNI | NULL    |                |
| password | varchar(32)      | NO   |     | NULL    |                |

#### Tasks

| Field      | Type             | Null | Key | Default | Extra          |
|------------|------------------|------|-----|---------|----------------|
| task_id    | int(10) unsigned | NO   | PRI | NULL    | auto_increment |
| account_id | int(10) unsigned | NO   | MUL | NULL    |                |
| tasks_name | varchar(256)     | NO   |     | NULL    |                |
| category   | varchar(256)     | NO   |     | NULL    |                |
| deadline   | date             | NO   |     | NULL    |                |
| priority   | int(11)          | NO   |     | NULL    |                |

---

Please add comments on what needs to be changed

**Comment by aakhare** [comment]
My suggestions are as follows: 

1. Replace "id" in the Accounts table as "account_id" for consistency across both tables 
2. Make "priority" a string type in Tasks table
3. Add "completed" field that will take a boolean value 
4. Replace "name" as "username" in Accounts table

**Comment by loshprung** [comment]
I'll also add that I think "tasks_name" should be changed to "task_name"

**Comment by loshprung** [comment]
Ok. The new tables will have the following format. Changes are bolded

#### Accounts

| Field    | Type             | Null | Key | Default | Extra          |
|----------|------------------|------|-----|---------|----------------|
| **account_id**       | int(10) unsigned | NO   | PRI | NULL    | auto_increment |
| **username**     | varchar(256)     | NO   | UNI | NULL    |                |
| password | varchar(32)      | NO   |     | NULL    |                |

#### Tasks

| Field      | Type             | Null | Key | Default | Extra          |
|------------|------------------|------|-----|---------|----------------|
| task_id    | int(10) unsigned | NO   | PRI | NULL    | auto_increment |
| account_id | int(10) unsigned | NO   | MUL | NULL    |                |
| **task_name** | varchar(256)     | NO   |     | NULL    |                |
| category   | varchar(256)     | NO   |     | NULL    |                |
| deadline   | date             | NO   |     | NULL    |                |
| priority   | **varchar(32)**          | NO   |     | NULL    |               |
| **completed**   | tinyint(1)          | NO   |     | 0    |               |

Note that type `varchar` indicates a string and type `tinyint` indicates a boolean
